# https://docs.astral.sh/uv/guides/integration/github/#installation

name: tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  linting:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v4
      - name: Set up UV and Python ${{ matrix.python-version }}
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.12"
      # You can test your matrix by printing the current Python version
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Lint
        run: |
          # Check for syntax errors or undefined names
          # uv run --extra=dev flake8 . --count --select=E9,F63,F7,F82,F401 --show-source --statistics
          # Make sure black code formatting is applied
          uv run --extra=dev black --check --preview src/
          # Make sure import orders are correct
          uv run --extra=dev isort --check src/
  type-checking:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    needs: linting
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14.0-beta.4", "pypy3.11"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up UV and Python ${{ matrix.python-version }}
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}
      # You can test your matrix by printing the current Python version
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Run tests
        run: uv run --extra=dev mypy
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    needs: [linting, type-checking]
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14.0-beta.4", "pypy3.11"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up UV and Python ${{ matrix.python-version }}
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}
      # You can test your matrix by printing the current Python version
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Run tests
        run: uv run --extra=dev pytest
