# https://docs.astral.sh/uv/guides/integration/github/#installation

name: tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  linting:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v4
      - name: Set up UV and Python ${{ matrix.python-version }}
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.12"
      # You can test your matrix by printing the current Python version
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Ruff linting
        run: uv run --dev ruff check src/ tests/
      - name: Enforce formatting standards
        run: uv run --dev black --check --preview src/ tests/
      - name: Enforce import sorting
        run: uv run --dev isort --check src/ tests/
  type-checking:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    needs: linting
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up UV and Python ${{ matrix.python-version }}
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}
      # You can test your matrix by printing the current Python version
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Run tests
        run: uv run --dev mypy
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    needs: [linting, type-checking]
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up UV and Python ${{ matrix.python-version }}
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}
      # You can test your matrix by printing the current Python version
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Run tests
        run: uv run --dev pytest
